### ISSUE TITLE
hw01 ready for grading

### ISSUE THREAD

**Issue by Jennica416** [Jennica416/STAT545-hw01-Nichols-Jennica#1]
@vincenzocoia @gvdr @ksedivyhaley @joeybernhardt @mynamedaike @pgonzaleze @derekcho

**Comment by arthursunbao** [comment]
@Jennica416 

Hi Jennica,

Nice to see your try on R for the README.MD, which is awesome. You got the bold, hyperlinks and paragraph work in it and I can see you are quite new in R :)

A little bit of advise is that you can try to add some pictures and more links to make your README.MD more lively. Also you can reflect some thoughts about how hard is the work for you.

Regards
Jason

**Comment by nicolehawe** [comment]
Hey Jennica,

I thought your readme was very well done, with a lot of interesting details about yourself. However, a little more exploration into the features on markdown would have added even more to this document. 
For the gapminder portion of the assignment you saved both the .md and .Rmd files correctly as well as added an adequate explanation on how you edited this. 
I would have liked to hear what you found difficult or easy about the assignment and possibly the solutions you discovered along the way.

Overall great job!!

Nicole

**Comment by mynamedaike** [comment]
Hello @Jennica416  ,

Proper self-introduction: Yes
4 or more aspects of the Markdown syntax: Yes
Process report and reflections: Yes
Gapminder exploration: Yes
Correctly named issue: Yes
SHA: No
Link to the work to be reviewed: No

Good job. You used more than 4 aspects of the Markdown syntax including section headers, links, bold, italic, bullet points, etc. You did some exploration on Gapminder and reported the process how you did your work. Try to include the SHA and a link to the work to be reviewed in the homework submission issue next time.
