### ISSUE TITLE
hw02 ready for grading

### ISSUE THREAD

**Issue by Jennica416** [Jennica416/STAT545-hw01-Nichols-Jennica#3]
@vincenzocoia @gvdr @ksedivyhaley @joeybernhardt @mynamedaike @pgonzaleze @derekcho

I used the same repository, with all Homework 2 assignment in it's own folder (hw02).

**Comment by ghost** [comment]
Hi @Jennica416,

You can find my peer review here #4 .

Cheers,

Alexi

**Comment by julianheavyside** [comment]
Hey @Jennica416 

I've added my review in issue #5 

Good job!
@julianheavyside
